name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 (Temurin distribution)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Compile application source files
      - name: Compile application source files
        run: |
          # Compile all Java source files
          javac -d out $(find src/main/java -name "*.java")

      # Step 4: Compile test files
      - name: Compile test files
        run: |
          # Compile test files with classpath set to the compiled source files
          javac -cp out -d out $(find src/test/java -name "*.java")

      # Step 5: Run the HelloWorld application
      - name: Run HelloWorld application
        run: |
          # Run the HelloWorld class
          java -cp out com.mycompany.app.HelloWorld

      # Step 6: Run tests
      - name: Run HelloWorldTest
        run: |
          # Run the HelloWorldTest class
          java -cp out com.mycompany.app.HelloWorldTest
