name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest  # Set the environment to Ubuntu

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 (Temurin distribution)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Use Temurin JDK 11

      # Step 3: Compile Java files
      - name: Compile Java application
        run: |
          # Compile Java files (including HelloWorld)
          javac -d out src/*.java

      # Step 4: Run HelloWorld application
      - name: Run HelloWorld application
        run: |
          # Run the HelloWorld class (or any other class with a main method)
          java -cp out HelloWorld
