name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Use Temurin JDK 11

      # Step 3: Compile all Java files
      - name: Compile Java application and tests
        run: |
          # Compile Java files (application and tests)
          javac -d out -cp "libs/*" src/*.java

      # Step 4: Run HelloWorld application (Optional, if you want to run it)
      - name: Run HelloWorld application
        run: |
          # Run the HelloWorld class
          java -cp out HelloWorld

      # Step 5: Run tests using JUnit 5
      - name: Run tests using JUnit 5
        run: |
          # Run tests (this runs all test classes)
          
